# Generated by Django 4.0.6 on 2023-01-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0004_grocery_unique_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='username',
            field=models.CharField(default='defaultuser', max_length=30),
        ),
        migrations.AddField(
            model_name='grocerylistitem',
            name='username',
            field=models.CharField(default='defaultuser', max_length=30),
        ),
    ]
