# Generated by Django 4.0.6 on 2023-01-13 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0005_grocery_username_grocerylistitem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='username',
            field=models.CharField(default='defaultuser', max_length=100),
        ),
        migrations.AlterField(
            model_name='grocerylistitem',
            name='username',
            field=models.CharField(default='defaultuser', max_length=100),
        ),
    ]
